# Name of your site (displayed in the header)
name: DocLine

# Short bio or description (displayed in the header)
description: DocLine research project

css:
  css:
    - /assets/css/default_github_style.css
    - /assets/css/justify.css
